version: '3'
services:
  transaction_service:
    build: ./transaction_service
    ports:
      - "5001:5001"

  analysis_service:
    build: ./analysis_service
    ports:
      - "5002:5002"

  scoring_service:
    build: ./scoring_service
    ports:
      - "5003:5003"

volumes:
  db_data:





